SWAGGER_HOST:
SWAGGER_URL:

app:
    server:
        port: 8000
        # false:debugMode, true:releaseMode
        gin-release: fasle
        # false:do not init DB, true:do init DB
        # If you already have tables and values
        # you do not need to initialize them.
        db-init: true
    db:
        dbms: postgres
        host: localhost
        port: 5432
        db: mailer
        user: postgres
        password: 1234
    smtp:
        host: host
        port: 1234
        user: user
        password: password
        vertification: false
    scheduler:
        time-second: 10 
